In [93]:
import pandas as pd
import numpy as np

In [94]:
 np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [95]:
## create a DataFrame
df=pd.DataFrame(data= np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['column1', 'column2', 'column3', 'column4'])

In [96]:
type(df)

pandas.core.frame.DataFrame

In [97]:
# the first five row of the data
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [98]:
# the last five row of the data
df.tail()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [99]:
#taking some rows of the data
df[["column1","column2","column3"]]

column1  column2  column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [100]:
#taking some rows of the data
df[["column1","column2"]]

column1  column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [101]:
# taking two columns of the data
df[["column1","column3"]]

column1  column3
Row1        0        2
Row2        4        6
Row3        8       10
Row4       12       14
Row5       16       18

In [102]:
# taking one columns of the data
df["column1"]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: column1, dtype: int32

In [103]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [104]:
type(df[["column1"]])

pandas.core.frame.DataFrame

In [105]:
df["column1"]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: column1, dtype: int32

In [106]:
type(df["column1"])

pandas.core.series.Series

In [107]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [108]:
df.loc[["Row1","Row3"]]

column1  column2  column3  column4
Row1        0        1        2        3
Row3        8        9       10       11

In [109]:
type(df.loc[["Row1","Row3"]])

pandas.core.frame.DataFrame

In [110]:
df.iloc[0:3]

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11

In [111]:
df.iloc[0:3,0:2]

column1  column2
Row1        0        1
Row2        4        5
Row3        8        9

In [112]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [113]:
df.iloc

In [114]:
df.iloc[2:4,1:3]

column2  column3
Row3        9       10
Row4       13       14

In [115]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [116]:
np.nan

nan

In [117]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],index=["Row1",
                                                    "Row2","Row3"],columns=["column1",
                                                                            "column2",
                                                                            "column3"
                                                                           ])                                             

In [118]:
df

column1  column2  column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [119]:
df.isnull()

column1  column2  column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [120]:
df.isna

<bound method DataFrame.isna of       column1  column2  column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3>

In [121]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [122]:
type(np.nan)

float

In [123]:
df

column1  column2  column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  3 non-null      int64  
 1   column2  2 non-null      float64
 2   column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes


In [125]:
df.head()

column1  column2  column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [126]:
## value count in series
df["column1"].value_counts()

1    2
5    1
Name: column1, dtype: int64

In [127]:
df["column1"].nunique()

2

In [128]:
df = pd.DataFrame({"A": [1, 2, 3], "B": [1, 1, 1]})

In [129]:
df

A  B
0  1  1
1  2  1
2  3  1

In [130]:
df["A"].unique()

array([1, 2, 3], dtype=int64)

In [131]:
df.nunique(axis=0)

A    3
B    1
dtype: int64

In [132]:
df.nunique(axis=1)

0    1
1    2
2    2
dtype: int64

In [133]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],index=["Row1",
                                                    "Row2","Row3"],columns=["column1",
                                                                            "column2",
                                                                            "column3"
                                                                           ])                                             

In [134]:
## create a DataFrame
df=pd.DataFrame(data= np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['columns1', 'columns2', 'columns3', 'columns4'])

In [135]:
df

columns1  columns2  columns3  columns4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [136]:
df["columns2"]>5

Row1    False
Row2    False
Row3     True
Row4     True
Row5     True
Name: columns2, dtype: bool

In [137]:
df[df["columns2"]>5]

columns1  columns2  columns3  columns4
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [138]:
df[df.isnull()]

columns1  columns2  columns3  columns4
Row1       NaN       NaN       NaN       NaN
Row2       NaN       NaN       NaN       NaN
Row3       NaN       NaN       NaN       NaN
Row4       NaN       NaN       NaN       NaN
Row5       NaN       NaN       NaN       NaN